version: "3.9"
services:
  backend:
    image: mirela28/thesharehub-backend:latest
    ports:
      - "8080:8080"

  frontend:
    image: mirela28/thesharehub-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

