name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
  
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Build and Push Docker Images
      uses: mr-smithers-excellent/docker-build-push@v6
      with: 
        image: mirela28/thesharehub
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        

  frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: backend

    steps:
    - uses: actions/checkout@v4
      with:
        repository: Mirela28/thesharehub-frontend
        path: frontend

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        
    - name: Install dependencies
      run: cd frontend && npm ci

    - name: Build frontend
      run: cd frontend && npm run build
      

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    
